// Code generated by "stringer -type=Activation"; DO NOT EDIT.

package seafan

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Linear-0]
	_ = x[Relu-1]
	_ = x[LeakyRelu-2]
	_ = x[Sigmoid-3]
	_ = x[SoftMax-4]
}

const _Activation_name = "LinearReluLeakyReluSigmoidSoftMax"

var _Activation_index = [...]uint8{0, 6, 10, 19, 26, 33}

func (i Activation) String() string {
	if i < 0 || i >= Activation(len(_Activation_index)-1) {
		return "Activation(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Activation_name[_Activation_index[i]:_Activation_index[i+1]]
}
