// Code generated by "stringer -type=FRole"; DO NOT EDIT.

package seafan

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FRCts-0]
	_ = x[FRCat-1]
	_ = x[FROneHot-2]
	_ = x[FREmbed-3]
	_ = x[FREither-4]
}

const _FRole_name = "FRCtsFRCatFROneHotFREmbedFREither"

var _FRole_index = [...]uint8{0, 5, 10, 18, 25, 33}

func (i FRole) String() string {
	if i < 0 || i >= FRole(len(_FRole_index)-1) {
		return "FRole(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FRole_name[_FRole_index[i]:_FRole_index[i+1]]
}
