// Code generated by "stringer -type=JoinType"; DO NOT EDIT.

package seafan

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Inner-0]
	_ = x[Left-1]
	_ = x[Right-2]
	_ = x[Outer-3]
}

const _JoinType_name = "InnerLeftRightOuter"

var _JoinType_index = [...]uint8{0, 5, 9, 14, 19}

func (i JoinType) String() string {
	if i < 0 || i >= JoinType(len(_JoinType_index)-1) {
		return "JoinType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _JoinType_name[_JoinType_index[i]:_JoinType_index[i+1]]
}
