// Code generated by "stringer -type=Layer"; DO NOT EDIT.

package seafan

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Input-0]
	_ = x[FC-1]
	_ = x[DropOut-2]
	_ = x[Target-3]
}

const _Layer_name = "InputFCDropOutTarget"

var _Layer_index = [...]uint8{0, 5, 7, 14, 20}

func (i Layer) String() string {
	if i < 0 || i >= Layer(len(_Layer_index)-1) {
		return "Layer(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Layer_name[_Layer_index[i]:_Layer_index[i+1]]
}
